os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Release

init:
  - cmake --version
  - msbuild /version

install:
  - git submodule update --init --recursive

build_script:
  - md build
  - cd build
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..
  - cmake --build . --config %configuration%

test_script:
  - ctest -C %configuration% -VV
