language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      addons: { apt: { packages: [g++-6], sources: [ubuntu-toolchain-r-test] } }
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" BUILD_TYPE=Release

    - os: linux
      dist: trusty
      addons: { apt: { packages: [g++-6, lcov], sources: [ubuntu-toolchain-r-test] } }
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6" BUILD_TYPE=Coverage GCOV=gcov-6

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build .
  - ctest -VV .

after_success:
  - ${TRAVIS_BUILD_DIR}/ci/travis-coverage.sh

notifications:
  email: false
